### ISSUE TITLE
Trying to build a reproducible environment with Nix

### ISSUE THREAD

**Issue by thomasjm** [evcxr/evcxr#307]
Hi, I'm working on building reproducible `evcxr` environments in Nix (PR [here](https://github.com/NixOS/nixpkgs/pull/236407)) and ran into a bit of trouble.

The idea is that the user specifies some packages they want, like `rand = "*"`. We then invoke some Nix machinery to build a 
`Cargo.toml` and `Cargo.lock` file, and then vendor all the dependencies to different folders on disk. At the end of the day I sort all the dependencies in topological order, and generate an `init.evcxr` file like this:

<details>
  <summary>init.evcxr</summary>

```
:offline 1
:dep cfg-if = { path = "/nix/store/44d4b4533ydszs27h6488w39sg3m7ivb-cargo-vendor-dir/cfg-if-1.0.0" }
:dep wasi = { path = "/nix/store/44d4b4533ydszs27h6488w39sg3m7ivb-cargo-vendor-dir/wasi-0.11.0+wasi-snapshot-preview1" }
:dep libc = { path = "/nix/store/44d4b4533ydszs27h6488w39sg3m7ivb-cargo-vendor-dir/libc-0.2.145" }
:dep getrandom = { path = "/nix/store/44d4b4533ydszs27h6488w39sg3m7ivb-cargo-vendor-dir/getrandom-0.2.9" }
:dep ppv-lite86 = { path = "/nix/store/44d4b4533ydszs27h6488w39sg3m7ivb-cargo-vendor-dir/ppv-lite86-0.2.17" }
:dep rand_core = { path = "/nix/store/44d4b4533ydszs27h6488w39sg3m7ivb-cargo-vendor-dir/rand_core-0.6.4" }
:dep rand_chacha = { path = "/nix/store/44d4b4533ydszs27h6488w39sg3m7ivb-cargo-vendor-dir/rand_chacha-0.3.1" }
:dep rand = { path = "/nix/store/44d4b4533ydszs27h6488w39sg3m7ivb-cargo-vendor-dir/rand-0.8.5" }
```

</details>

My goal here is that in the `evcxr` session, the user will be able to type `use rand` and be off and running. However, this sequence of `:dep` calls doesn't work properly and I'm not sure why. If I type these lines one by one into a fresh session, it looks like this:

<details>
  <summary>example session</summary>

```
Welcome to evcxr. For help, type :help
>> :offline 1
Offline mode: true

>> :dep cfg-if = { path = "/nix/store/44d4b4533ydszs27h6488w39sg3m7ivb-cargo-vendor-dir/cfg-if-1.0.0" }
>> :dep wasi = { path = "/nix/store/44d4b4533ydszs27h6488w39sg3m7ivb-cargo-vendor-dir/wasi-0.11.0+wasi-snapshot-preview1" }
>> :dep libc = { path = "/nix/store/44d4b4533ydszs27h6488w39sg3m7ivb-cargo-vendor-dir/libc-0.2.145" }
>> :dep getrandom = { path = "/nix/store/44d4b4533ydszs27h6488w39sg3m7ivb-cargo-vendor-dir/getrandom-0.2.9" }
Error: error: failed to get `cfg-if`
    ... which satisfies path dependency `getrandom` of package `evcxr_dummy_validate_dep v0.0.1 (/tmp/.tmpC2FfmW)`

Caused by:
  failed to create directory `/nix/store/zkhwvyfd7hk3gfy7az1z9r5anqn7nncv-cargo-home/home/registry/index/github.com-1ecc6299db9ec823`

Caused by:
  Permission denied (os error 13)
>> 
```

</details>

In this example, `getrandom` is the first one with nontrivial dependencies -- it depends on `cfg-if`. But it crashes, even though I just provided a `:dep cfg-if` command and it seemed happy with it? Any help would be much appreciated.

**Comment by thomasjm** [comment]
P.S. In case it's relevant, I'm also setting `CARGO_HOME` to a directory with the original `Cargo.toml`/`Cargo.lock`, as well as a `.cargo/config.toml` file with some extra Cargo config like this:

```toml
[source.crates-io]
replace-with = "vendored-sources"

[source.vendored-sources]
local-registry = "/nix/store/.../some/index/path"

[net]
offline = true
```

**Comment by davidlattimore** [comment]
To debug this, I'd suggest setting `EVCXR_TMPDIR=$HOME/tmp/e1` (or something like that), then running `evcxr`. Once it fails, `cd $EVCXR_TMPDIR` and try doing a `cargo build` to see if it gives the same error. If it does, you can try editing `Cargo.toml` to see what would be required to make it succeed.

**Comment by davidlattimore** [comment]
Something else I should mention is that adding lots of `:dep` commands will make `evcxr` startup pretty slow, since it will compile them all each time it starts - also rust-analzyer will analyse them all each time `evcxr` starts.

If you're specifying a custom local registry, do you need to specify the path to the package? Assuming there's only one version in the registry, I'd expect that you could just write:
```
:dep rand
rand::random::<u8>()
```

**Comment by thomasjm** [comment]
Thanks for the quick response! I tried the `EVCXR_TMPDIR` thing and examined the `Cargo.toml` after each step. After the first few deps (`cfg-if`, `wasi`, and `libc`) they're all present:

<details>
  <summary>after first 3 :dep calls</summary>

```toml
[package]
name = "ctx"
version = "1.0.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]
path = "src/lib.rs"

[profile.dev]
opt-level = 2
debug = false
rpath = true
lto = false
debug-assertions = true
codegen-units = 16
panic = 'unwind'
incremental = true
overflow-checks = true

[dependencies]
wasi = { path = "/nix/store/44d4b4533ydszs27h6488w39sg3m7ivb-cargo-vendor-dir/wasi-0.11.0+wasi-snapshot-preview1" }
libc = { path = "/nix/store/44d4b4533ydszs27h6488w39sg3m7ivb-cargo-vendor-dir/libc-0.2.145" }
cfg-if = { path = "/nix/store/44d4b4533ydszs27h6488w39sg3m7ivb-cargo-vendor-dir/cfg-if-1.0.0" }
```

</details>

Then, after trying to add `getrandom`, the `Cargo.toml` changes abruptly and the other dependencies disappear:

<details>
  <summary>after :dep getrandom call</summary>

```toml
    [package]
    name = "evcxr_dummy_validate_dep"
    version = "0.0.1"
    edition = "2021"

    [lib]
    path = "lib.rs"

    [dependencies]
    getrandom = { path = "/nix/store/44d4b4533ydszs27h6488w39sg3m7ivb-cargo-vendor-dir/getrandom-0.2.9" }
```

</details>

Reading between the lines here... is it possible that `evcxr` is doing a "validation step" on each `:dep` call where it produces a `Cargo.toml` package called `evcxr_dummy_validate_dep` with only that dependency? And then only if that succeeds does it add the dependency to the main file with package name `ctx`?

> If you're specifying a custom local registry, do you need to specify the path to the package?

I hope I can get it to work that way. I'll definitely try, probably after the basics are working with manual `:dep` calls.
